name: Actions commands

on: [push]

jobs:
  run-actions-commands:
    runs-on: ubuntu-latest
    steps:
      - name: list Names
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "{{ github.token }}""