name: Actions commands

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list Names
        run: |
          git clone https://adaparec:9d0ea93911ba2e36de56caeba64a6a7ad0031c72/github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_SHA