name: Actions commands

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list Names
        run: |
          git clone https://github.com/adaparec:$GITHUB_TOKEN/$GITHUB_REPOSITORY
          git checkout $GITHUB_SHA