name: Actions commands

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list Names
        env:
          GITHUB_TOKEN_ACTION: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://adaparec:$GITHUB_TOKEN_ACTION@github.com/adaparec/github-actions.git
          git checkout $GITHUB_SHA