name: Actions commands

on: [push]

jobs:
  run-actions-commands:
    runs-on: ubuntu-latest
    steps:
      - name: list Names
        run: |
          pwd
          ls -a
      - name: GitHub Checkout
        uses: actions/checkout@v1
      - name: list Names after Checkout
        run: |
          pwd
          ls -a